# Use a basic Python image
FROM python:3.12-slim

# Install LightGBM
RUN pip install lightgbm

# Copy the LightGBM model
COPY model.txt /models/model.txt

# Copy the inference script
COPY inference.py /app/inference.py

# Set the entrypoint to the inference script
ENTRYPOINT ["python", "/app/inference.py", "--model_path", "/models/model.txt"]