# Use TensorFlow Serving base image
FROM tensorflow/serving

# Copy the TensorFlow model
COPY model /models/model

# Expose the necessary port
EXPOSE 8501

# Set the entrypoint for TensorFlow Serving
ENTRYPOINT ["tensorflow_model_server", "--rest_api_port=8501", "--model_name=model", "--model_base_path=/models/model"]