# Use a basic Python image
FROM python:3.12-slim

# Install scikit-learn
RUN pip install scikit-learn

# Copy the Scikit-learn model
COPY model.pkl /models/model.pkl

# Copy the inference script
COPY inference.py /app/inference.py

# Set the entrypoint to the inference script
ENTRYPOINT ["python", "/app/inference.py", "--model_path", "/models/model.pkl"]