# Use a basic Python image
FROM python:3.12-slim

# Install CatBoost
RUN pip install catboost

# Copy the CatBoost model
COPY model.cbm /models/model.cbm

# Copy the inference script
COPY inference.py /app/inference.py

# Set the entrypoint to the inference script
ENTRYPOINT ["python", "/app/inference.py", "--model_path", "/models/model.cbm"]