# Use a basic Python image
FROM python:3.12-slim

# Install PyTorch
RUN pip install torch torchvision

# Copy the PyTorch model
COPY model.pth /models/model.pth

# Copy the inference script
COPY inference.py /app/inference.py

# Set the entrypoint to the inference script
ENTRYPOINT ["python", "/app/inference.py", "--model_path", "/models/model.pth"]