# Base image with Miniconda
FROM continuumio/miniconda3

# Set environment variables
ENV PATH /opt/conda/envs/nicegui_env/bin:$PATH

# Copy environment.yml if using conda as a base
COPY ./code/framework/frontend/environment.yml /tmp/environment.yml

# Create Conda environment for FeatherML
RUN conda env create -f /tmp/environment.yml

# Activate the environment
SHELL ["conda", "activate", "nicegui_env"]

# Set the workdir and copy the project files
WORKDIR /app
COPY ./code/framework/frontend /app

# Expose the port
EXPOSE 5001

# Entry point that ensures the Conda environment is fully activated
CMD ["python", "demo.py"]