# Use the official Miniconda3 image as the base
FROM continuumio/miniconda3

# Copy the environment.yml to a temporary location
COPY ./code/framework/frontend/environment.yml /tmp/

# Create Conda environment for FeatherML
RUN conda env create -f /tmp/environment.yml

# Clean up conda packages to reduce image size
RUN conda clean -afy

# Set environment variables
ENV PYTHONPATH="/app"

# Set the working directory
WORKDIR /app

# Copy the project files into /app
COPY ./code/framework/frontend/ /app

# Activate the environment
# SHELL ["conda", "run", "-n", "nicegui_env", "/bin/bash", "-c"]

# Expose port 5002 to the host
EXPOSE 5002

# Set the command to activate the environment and run demo.py
# CMD ["python", "demo.py"]

# Set the command to run demo.py within the conda environment
CMD ["conda", "run", "--no-capture-output", "-n", "nicegui_env", "python", "demo.py"]
