name: nicegui_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - requests
  - prometheus_client
  - grafana-client
  - fastapi
  - plotly
  - pandas
  - uvicorn
  - pydantic
  - elasticsearch
  - pip
  - pip:
      - nicegui
