name: nicegui_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - requests
  - prometheus_client
  - grafana-client
  - pip
  - pip:
      - nicegui
      - fastapi
      - uvicorn
      - pydantic
      - elasticsearch
